name: Sample Book App

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/build

  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    name: Deploy to Dev
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/deploy
        with:
          environment: dev
          port: 8001

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    name: Test on Dev
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/test
        with:
          environment: dev

  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    name: Deploy to staging
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/deploy
        with:
          environment: staging
          port: 8002

  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    name: Test on staging
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/test
        with:
          environment: staging

  deploy-pre-prd:
    runs-on: self-hosted
    needs: [test-stg]
    name: Deploy to pre prod
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: 8003

  test-pre-prd:
    runs-on: self-hosted
    needs: [deploy-pre-prd]
    name: Test on preprod
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/test
        with:
          environment: preprod

  deploy-prd:
    runs-on: self-hosted
    needs: [test-pre-prd]
    name: Deploy to production
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: 8004

  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: ./.github/actions/test
        with:
          environment: preprod